---
# Install and configure a new Macbook

- name: change hostname
  shell: hostname {{ hostname }}
  become: yes
  become_user: root
  tags:
    - configuration

- name: add hostname to local DNS
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.1.1	{{ hostname }}.localdomain	{{ hostname }}
  become: yes
  become_user: root
  tags:
    - configuration

- name: generate ssh key
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  tags:
    - configuration

- name: install homebrew
  import_tasks: homebrew.yml

- name: install homebrew apps
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew_apps }}"
  tags:
    - installation

- name: install homebrew cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ cask_apps }}"
  tags:
    - installation

- name: install VirtualBox guest additions
  shell: vagrant plugin install vagrant-vbguest
  tags:
    - installation

- name: install atom
  import_tasks: atom.yml

- name: check if the mysql root password needs to be set.
  shell: if mysqladmin --user=root --password="" version; then rm -f /usr/local/var/log/mysql-root-user.done; mysql -uroot -e "UPDATE mysql.user SET Password = PASSWORD(\"{{ mysql_root_password }}\") WHERE User = \"root\"; DELETE FROM mysql.user WHERE User=\"\"; DELETE FROM mysql.user WHERE User=\"root\" AND Host NOT IN (\"localhost\", \"127.0.0.1\", \"::1\"); DROP DATABASE IF EXISTS test; FLUSH PRIVILEGES;"; touch /usr/local/var/log/mysql-root-user.done; fi
  args:
    creates: /usr/local/var/log/mysql-root-user.done
  tags:
    - configuration

- name: setup dotfiles
  get_url:
    url: "{{ dotfile_location }}/.{{ item }}"
    dest: {{ lookup('env','HOME') }}/.{{ item }}
  with_items: "{{ dotfiles }}"
  tags:
    - configuration
