- name: install homebrew
  include: homebrew.yml

- name: install homebrew apps
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew_apps }}"
  tags:
    - installation

- name: install homebrew cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ cask_apps }}"
  tags:
    - installation

- name: setup dotfiles
  get_url:
    url: "{{ dotfile_location }}/.{{ item }}"
    dest: /Users/{{ ansible_user }}/.{{ item }}
  with_items: "{{ dotfiles }}"
  tags:
    - config

- name: check if the root password needs to be set.
  shell: if mysqladmin --user=root --password="" version; then rm -f /usr/local/var/log/mysql-root-user.done; mysql -uroot -e "UPDATE mysql.user SET Password = PASSWORD(\"{{ mysql_root_password }}\") WHERE User = \"root\"; DELETE FROM mysql.user WHERE User=\"\"; DELETE FROM mysql.user WHERE User=\"root\" AND Host NOT IN (\"localhost\", \"127.0.0.1\", \"::1\"); DROP DATABASE IF EXISTS test; FLUSH PRIVILEGES;"; touch /usr/local/var/log/mysql-root-user.done; fi
  args:
    creates: /usr/local/var/log/mysql-root-user.done
  tags:
    - config

- name: install atom
  include: atom.yml
